# Generated by Django 4.1.3 on 2023-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easyaudit", "0016_alter_crudevent_event_type"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="crudevent",
            index_together=set(),
        ),
        migrations.AlterField(
            model_name="crudevent",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date time"
            ),
        ),
        migrations.AlterField(
            model_name="crudevent",
            name="object_id",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Object ID"
            ),
        ),
        migrations.AlterField(
            model_name="loginevent",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date time"
            ),
        ),
        migrations.AlterField(
            model_name="requestevent",
            name="datetime",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Date time"
            ),
        ),
        migrations.AddIndex(
            model_name="crudevent",
            index=models.Index(
                fields=["object_id", "object_repr"],
                name="easyaudit_c_object__49e5a0_idx",
            ),
        ),
    ]
