# Generated by Django 4.1.3 on 2023-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easyaudit", "0017_alter_crudevent_index_together_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crudevent",
            index=models.Index(
                fields=["object_id"], name="easyaudit_c_object__a12edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crudevent",
            index=models.Index(
                fields=["object_repr"], name="easyaudit_c_object__a807a2_idx"
            ),
        ),
    ]
